### ISSUE TITLE
Fix sanitization warning for card images

### ISSUE THREAD

**Issue by plural** [NetrunnerDB/NRDBv2#98]
WARNING: Binding style attributes may introduce cross-site scripting vulnerabilities; please ensure that values being bound are properly escaped. For more information, including how to disable this warning, see https://deprecations.emberjs.com/v1.x/#toc_binding-style-attributes. Style affected: "background-image: url(https://card-images.netrunnerdb.com/v1/small/21028.jpg)"

**Comment by locks** [comment]
Addressed!
